name: Tests y actualizar early

on:
  push:   
    branches:
      - main   # se ejecuta en cada commit en main

permissions:
  contents: write

jobs:
  test-and-update-early:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout completo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Ejecutar tests
        run: mvn clean test 

      - name: Merge main into early
        if: success()
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          git fetch origin
          git checkout early || git checkout -b early

          git reset --hard origin/main
          git push origin early --force