name: Test

on:
  push:
    branches:
      - main   # se ejecuta en cada commit en main

jobs:
  test-and-merge:
    runs-on: ubuntu-latest

    steps:
      #Clonar repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      #Configurar Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      #Ejecutar tests
      - name: Run tests
        run: |
          javac -d out $(find src/main/java src/test/java -name "*.java")
          java -cp out org.junit.runner.JUnitCore com.tt1.test.AppTest

      #Actualizar rama early si tests pasan
      - name: Merge main into early
        if: success()  # solo si los tests pasan
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin early
          git checkout early
          git merge --no-ff main -m "Auto-update early from main after tests passed"
          git push origin early